Proyect__colmena/Proyect__colmena/ViewModels/LineaVentaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyect__colmena.ViewModels
{
    public class LineaVentaViewModel
    {
        public int ProductoId { get; set; }
        public string ProductoNombre { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public bool Retirar { get; set; }

        public decimal Monto()
        {
            return Cantidad * PrecioUnitario;
        }
    }
}

Proyect__colmena/Proyect__colmena/ViewModels/VentaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proyect__colmena.ViewModels
{
    public class VentaViewModel
    {
        #region cabecera

        public string Cliente { get; set; }
        public int CabeceraProductoId { get; set; }
        public string CabeceraProductoNombre { get; set; }
        public int CabeceraProductoCantidad { get; set; }
        public decimal CabeceraProductoPrecio { get; set; }
        #endregion

        #region Contenido
        public List<LineaVentaViewModel> lineaVenta { get; set; }
        #endregion

        public VentaViewModel()
        {
            lineaVenta = new List<LineaVentaViewModel>();
            Refrescar();
        }

        public void AgregarItemADetalle()
        {
            lineaVenta.Add(new LineaVentaViewModel()
            {
                ProductoId = CabeceraProductoId,
                ProductoNombre = CabeceraProductoNombre,
                PrecioUnitario = CabeceraProductoPrecio,
                Cantidad = CabeceraProductoCantidad,
            });
            Refrescar();
        }

        public decimal Total()
        {
            return lineaVenta.Sum(x => x.Monto());
        }

        public void Refrescar()
        {
            CabeceraProductoId = 0;
            CabeceraProductoNombre = null;
            CabeceraProductoCantidad = 1;
            CabeceraProductoPrecio = 0;
        }
    }
}

Proyect__colmena/Proyect__colmena/Controllers/LoginController.cs
using System;
using System.Web.Mvc;
using Aplicacion;
using Dominio;


namespace Proyect__colmena.Controllers
{
    public class LoginController : Controller
    {
        private GestionarLoginService _gestionarLoginService = new GestionarLoginService();

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Index")]
        public ActionResult VerificarAcceso([Bind(Include = "UserName, Password")] Usuario u)
        {
            try
            {
                var usuario = _gestionarLoginService.VerificarAcceso(u.UserName, u.Password);
                return RedirectToAction("Home");
            }
            catch (ApplicationException a)
            {
                ViewBag.errorLogin = a.Message;
                return View();
            }
        }

        public ActionResult Home()
        {
            return View();
        }
    }
}

Proyect__colmena/Proyect__colmena/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Aplicacion;
using Dominio;

namespace Proyect__colmena.Controllers
{
    public class ProductoController : Controller
    {
        private readonly GestionarCategoriaService _gestionarCategoriaService = new GestionarCategoriaService();
        private readonly GestionarProductoService _gestionarProductoService = new GestionarProductoService();

        // GET: Producto
        public ActionResult Index()
        {
            List<Producto> listarProductos = _gestionarProductoService.ListarProductos();
            return View(listarProductos);
        }

        public ActionResult Create()
        {
            var listaCategorias = _gestionarCategoriaService.ListarCategorias();
            ViewBag.IdCategoria = new SelectList(listaCategorias, "IdCategoria", "Nombre");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Producto producto, string action, string xd)
        {
            bool insert = _gestionarProductoService.RegistrarProducto(producto);
            if (insert == true)
            {
               return RedirectToAction("Index");
            }

            return View();

            //return producto.IdProducto + " " + producto.Nombre + " " + producto.Descripcion + " " + producto.Categoria.IdCategoria;
        }

        public ActionResult Edit(int id)
        {
            var producto = _gestionarProductoService.BuscarProductoID(id);
            var listaCategorias = _gestionarCategoriaService.ListarCategorias();
            ViewBag.IdCategoria = new SelectList(listaCategorias, "IdCategoria", "Nombre", producto.Categoria.IdCategoria);
            return View(producto);
        }

        [HttpPost]
        public ActionResult Edit(Producto producto)
        {
            bool insert = _gestionarProductoService.EditarProducto(producto);
            return RedirectToAction("Index");
            //return producto.IdProducto + " " + producto.Nombre + " " + producto.Descripcion + " " + producto.Categoria.IdCategoria;
        }

        public ActionResult ProductoModal()
        {
            return PartialView();
        }
    }
}

Proyect__colmena/Proyect__colmena/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aplicacion;
using Dominio;
using Proyect__colmena.ViewModels;

namespace Proyect__colmena.Controllers
{
    public class VentaController : Controller
    {
        private GestionarVentaService _gestionarVentaService = new GestionarVentaService();
        GestionarClienteService _gestionarClienteService = new GestionarClienteService();

        public ActionResult Index()
        {
            var lista = _gestionarVentaService.ListarVentas();
            return View(lista); 
        }

        public ActionResult Create()
        {
           return View(new VentaViewModel());
        }

        [HttpPost]
        public ActionResult Create(VentaViewModel model, string action)
        {
            if (action.Equals("agregar_producto"))
            {
                model.AgregarItemADetalle();
            }
            return View(model);
        }

        public ActionResult ObtenerClientes()
        {
            var listaClientes = _gestionarClienteService.ListarClientes();
            return PartialView(listaClientes);
        }

        public PartialViewResult ListaClientes()
        {
            var listaClientes = _gestionarClienteService.ListarClientes();
            return PartialView(listaClientes);
        }
    }
}

Proyect__colmena/Proyect__colmena/Views/Login/Home.cshtml
@{
    Layout = "~/Views/Shared/Master_Layout.cshtml";
    ViewBag.Title = "Home";
}

<h2>Home</h2>

Proyect__colmena/Proyect__colmena/Views/Login/Index.cshtml
@model Dominio.Usuario
@{
    Layout = "~/Views/Shared/_Layout_Login.cshtml";
    ViewBag.Title = "Login";
}

@using (Html.BeginForm("Index", "Login", FormMethod.Post, new {@class = "login100-form validate-form"}))
{
    <div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
        <span class="label-input100">Username</span>
        @Html.EditorFor(model => model.UserName, new {htmlAttributes = new {@class = "input100", placeholder = "Enter Username"}})
        <span class="focus-input100"></span>
    </div>

    <div class="wrap-input100 validate-input m-b-18" data-validate="Password is required">
        <span class="label-input100">Password</span>
        @Html.EditorFor(model => model.Password, new {htmlAttributes = new {@class = "input100", placeholder = "Enter password", type = "password"}})
        <span class="focus-input100"></span>
    </div>

    <div class="flex-sb-m w-full p-b-30">
        <div class="contact100-form-checkbox">
            <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
            <label class="label-checkbox100" for="ckb1">
                Remember me
            </label>
        </div>

        <div>
            <a href="#" class="txt1">
                Forgot Password?
            </a>
        </div>
    </div>
    <p align="center" style="color: red">@ViewBag.errorLogin</p>
    <div class="container-login100-form-btn">
        <input type="submit" value="Login" class="login100-form-btn"/>
    </div>
}

Proyect__colmena/Proyect__colmena/Views/Producto/Create.cshtml
@model Dominio.Producto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Producto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Categoria.IdCategoria, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.DropDownListFor(model => model.Categoria.IdCategoria, ViewBag.IdCategoria as SelectList, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categoria.IdCategoria, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <p>DETALLE DEL PRODUCTO</p>

    <div class="form-group">
        @Html.LabelFor(model => model.DetalleProducto.PrecioCosto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DetalleProducto.PrecioCosto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DetalleProducto.PrecioCosto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DetalleProducto.PrecioVenta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DetalleProducto.PrecioVenta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DetalleProducto.PrecioVenta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DetalleProducto.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DetalleProducto.Stock, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DetalleProducto.Stock, "", new { @class = "text-danger" })
        </div>
    </div>
    <input type="text" class="btn btn-default" name="xd" />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" name="action" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Proyect__colmena/Proyect__colmena/Views/Producto/Edit.cshtml
@model Dominio.Producto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Producto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdProducto)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Categoria.IdCategoria, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.DropDownListFor(model => model.Categoria.IdCategoria, ViewBag.IdCategoria as SelectList, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categoria.IdCategoria, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    
    <p>Detalle de producto</p>
    
    @Html.HiddenFor(model => model.DetalleProducto.IdDetalleProducto)
    <div class="form-group">
        @Html.LabelFor(model => model.DetalleProducto.PrecioCosto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DetalleProducto.PrecioCosto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DetalleProducto.PrecioCosto, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.DetalleProducto.PrecioVenta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DetalleProducto.PrecioVenta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DetalleProducto.PrecioVenta, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.DetalleProducto.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DetalleProducto.Stock, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DetalleProducto.Stock, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Proyect__colmena/Proyect__colmena/Views/Producto/Index.cshtml
@using Dominio
@model IEnumerable<Dominio.Producto>

@{
    Layout = "~/Views/Shared/Master_Layout.cshtml";
    ViewBag.Title = "Listar Categorias";
}

<div style="float:left">
    <b>Productos:</b>
</div>
<br />


@Html.Partial("ProductoModal")
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#miModal">
    Abrir modal
</button>

<table class="table table-bordered table-striped table-hover js-basic-example dataTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.DetalleProducto.PrecioCosto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DetalleProducto.PrecioVenta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DetalleProducto.Stock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.Nombre)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DetalleProducto.PrecioCosto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DetalleProducto.PrecioVenta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DetalleProducto.Stock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.Nombre)
            </td>

            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.IdProducto }) |
                <!--Html.ActionLink("Bloquear", "BloquearPersonaCorriente", new { idPersonaCorriente = item.personaCorrienteID })-->
            </td>
        </tr>
    }

</table>

Proyect__colmena/Proyect__colmena/Views/Producto/ProductoModal.cshtml
<div class="modal fade" id="miModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Esto es un modal</h4>
            </div>
            <div class="modal-body">
                Texto del modal
            </div>
        </div>
    </div>
</div>

Proyect__colmena/Proyect__colmena/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            </ul>
        </div>
    </div>
</div>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>

Proyect__colmena/Proyect__colmena/Views/Venta/Create.cshtml
@using Dominio
@model Proyect__colmena.ViewModels.VentaViewModel

@{
    Layout = "~/Views/Shared/Master_Layout.cshtml";
    ViewBag.Title = "Create";
}

<div class="modal fade" id="ListaClientes" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div id="ContenidoModal_Clientes"></div>
        </div>
    </div>
</div>

@using (Html.BeginForm("Create", "Venta", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <table id="encabezado" class="table">
        <thead>
        <tr style="font-size:20px;">
            <th>Id Venta <input style="color:red; font-size:12px;" class="form-control" type="text" id="id_venta" readonly /></th>
            <th>
                Fecha
                <input style="color:red;font-size:20px;" class="form-control" type="text" id="id_fecha" readonly value="@DateTime.Now.Year-@DateTime.Now.Month-@DateTime.Now.Day @DateTime.Now.Hour:@DateTime.Now.Minute:@DateTime.Now.Second" />

            </th>
        </tr>
        </thead>
        <tbody>
        <tr style="font-size:20px;">
            <td>
                Detalles del Cliente
                    <input class="btn btn-warning btn-lg col-md-12" type="button" name="enlace_cliente" value="Obtener Cliente" 
                           data-toggle="modal" data-target="#ListaClientes" onclick="javascript: muestraModal();"/>
                
            </td>
            <td>
                Modo de Pago
                <div class="col-md-12 dropdown">
                    @* @Html.DropDownList("modoPago", ViewBag.ListaModoPago as SelectList, "Seleccione Modo Pago", htmlAttributes: new { @class = "form-control", @required = "required" })*@
                </div>
            </td>
        </tr>
        <tr style="font-size:20px;">

            <td>Nombre Cliente <input style="font-size:20px; font-weight:700;" class="form-control" type="text" id="txtNombreCliente" readonly required /></td>
            <td>
                DNI
                <input type="hidden" id="txtCodigoCliente">
                <input style="font-size:20px; font-weight:700;" class="form-control" type="text" id="txtDniCliente" readonly required />
            </td>
        </tr>
       
        </tbody>
    </table>


    <div class="row">
        <div class="col-xs-12">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(x => x.Cliente)
                @Html.TextBoxFor(x => x.Cliente, new { @class = "form-control", placeholder = "Ingrese el nombre del cliente" })
                @Html.ValidationMessage("Cliente", null, new { @class = "label label-danger" })
            </div>

            <div class="well well-sm">
                <div class="row">
                    <div class="col-xs-7">
                        @Html.EditorFor(model => model.CabeceraProductoId)
                        @Html.EditorFor(model => model.CabeceraProductoNombre, new { htmlAttributes = new { @class = "form-control", id = "Producto" } })
                        @Html.ValidationMessageFor(model => model.CabeceraProductoNombre, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-xs-2">
                        <div class="input-group">
                            @Html.TextBoxFor(x => x.CabeceraProductoCantidad, new { @class = "form-control", placeholder = "Cantidad" })
                        </div>
                    </div>

                    <div class="col-xs-2">
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">S/.</span>
                            @Html.TextBoxFor(x => x.CabeceraProductoPrecio, new { @class = "form-control", placeholder = "Precio" })
                        </div>
                    </div>

                    <div class="col-xs-1">
                        <button class="btn btn-primary" type="submit" value="agregar_producto" name="action">
                            <i class="glyphicon glyphicon-plus"></i>
                        </button>
                    </div>
                </div>
            </div>

            <hr />

            <ul id="facturador-detalle" class="list-group">
                @if (Model.lineaVenta.Count > 0)
                {
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-1"></div>
                            <div class="col-xs-5">
                                <b>Producto</b>
                            </div>
                            <div class="col-xs-2 text-center">
                                <b>Cantidad</b>
                            </div>
                            <div class="col-xs-2 text-right">
                                <b>Precio Unitario</b>
                            </div>
                            <div class="col-xs-2 text-right">
                                <b>Monto</b>
                            </div>
                        </div>
                    </li>
                }
                @foreach (var item in Model.lineaVenta)
                {
                    var i = Model.lineaVenta.IndexOf(item);
                    <li class="list-group-item">
                        <!-- Modelo -->
                        @Html.Hidden("lineaVenta[" + i + "].ProductoId", item.ProductoId)
                        @Html.Hidden("lineaVenta[" + i + "].ProductoNombre", item.ProductoNombre)
                        @Html.Hidden("lineaVenta[" + i + "].PrecioUnitario", item.PrecioUnitario)
                        @Html.Hidden("lineaVenta[" + i + "].Cantidad", item.Cantidad)
                        @Html.Hidden("lineaVenta[" + i + "].Retirar", item.Retirar, new { @class = "retirar" })

                        <div class="row">
                            <div class="col-xs-1 text-right">
                                <button class="btn btn-danger btn-xs btn-block btn-retirar" type="submit" value="retirar_producto" name="action">
                                    <i class="glyphicon glyphicon-remove"></i>
                                </button>
                            </div>
                            <div class="col-xs-5">
                                @item.ProductoNombre
                            </div>
                            <div class="col-xs-2 text-center">
                                @item.Cantidad
                            </div>
                            <div class="col-xs-2 text-right">
                                @string.Format("{0:c}", item.PrecioUnitario)
                            </div>
                            <div class="col-xs-2 text-right">
                                @string.Format("{0:c}", item.Monto())
                            </div>
                        </div>
                    </li>
                }
                @if (Model.lineaVenta.Count > 0)
                {
                    <li class="list-group-item text-right" style="font-size:18px;">
                        @string.Format("{0:c}", Model.Total())
                    </li>
                }
            </ul>
            @if (Model.lineaVenta.Count > 0)
            {
                <button class="btn btn-primary btn-block btn-lg" type="submit" value="generar" name="action">Generar comprobante</button>
            }

        </div>
    </div>

}

@section Scripts{
    <script>
        $(document).ready(function () {
            LimpiarAgregarProducto();

            $(".btn-retirar").click(function () {
                if (confirm('¿Está seguro de retirar el item seleccionado?')) {
                    $(this).closest('.list-group-item').find('.retirar').val("True");
                    return true;
                }

                return false;
            })
            /* Autocomplete de producto, jquery UI */
            $("#Producto").autocomplete({
                dataType: 'JSON',
                source: function (request, response) {
                    jQuery.ajax({
                        url: '/Home/BuscarProducto',
                        type: "post",
                        dataType: "json",
                        data: {
                            nombre: request.term
                        },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return {
                                    id: item.id,
                                    value: item.Nombre,
                                    precio: item.Precio
                                }
                            }))
                        }
                    })
                },
                select: function (e, ui) {
                    $("#CabeceraProductoId").val(ui.item.id);
                    $("#CabeceraProductoPrecio").val(ui.item.precio);
                    $("#CabeceraProductoCantidad").focus();
                }
            })
        })

        function LimpiarAgregarProducto() {
            $("#CabeceraProductoId").val("");
            $("#Producto").val("");
            $("#CabeceraProductoPrecio").val("");
            $("#CabeceraProductoCantidad").val(1);
        }

        function muestraModal() {
            $('#ContenidoModal_Clientes').load('@Url.Action("ObtenerClientes")');
        }

        
    </script>
}

Proyect__colmena/Proyect__colmena/Views/Venta/ListaClientes.cshtml
@model IEnumerable<Dominio.Cliente>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dni)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dni)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>